spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    #    url: jdbc:mysql://192.168.30.113/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/contract_management?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    default-property-inclusion: non_null

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    password: falonie

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

file:
  upload-dir: E:/GoToWork/uploadPath

app:
  file:
    upload-dir: E:/GoToWork/uploadPath
    storage:
      mapping: E:/GoToWork/uploadPath